### ISSUE TITLE
App will not connect 

### ISSUE THREAD

**Issue by acdcfan** [lukealford/aussiebb_tray#11]
So when I click on the link to start it, it shows up the window with "getting your service id" "Figuring POI" and spinning circle and than throws this error

```
Unhandled Promise Rejection
NonError: 'Could not get POI list'
    at module.exports.input (/Applications/aussiebb_aunt.app/Contents/Resources/app.asar/node_modules/ensure-error/index.js:14:10)
    at handleError (/Applications/aussiebb_aunt.app/Contents/Resources/app.asar/node_modules/electron-unhandled/index.js:21:10)
    at process.on.error (/Applications/aussiebb_aunt.app/Contents/Resources/app.asar/node_modules/electron-unhandled/index.js:100:4)
```

I can log in just fine with AussieBB app on my ipad and via web page

This is on my Mac running mojave

**Comment by fing3rguns** [comment]
This is in relation to the DDoS issue on the main webserver / api is having. 

It should pass as the heat / webservers come back up.

**Comment by lukealford** [comment]
Closing this as it seems to be working fine on my end now the DDoS issues have passed.
